#!/bin/bash
# install on a new OS
sudo apt update
sudo apt upgrade

# environment
sudo apt install csh
sudo apt install make
sudo apt install gcc
sudo apt install g++
sudo apt install git
sudo apt install gnuplot
sudo apt install remmina

# vim 8.0
sudo add-apt-repository ppa:jonathonf/vim
sudo apt update
sudo apt install vim

# Vundle
mkdir bundle ~/.vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/
# YCM
sudo apt-get install build-essential cmake
sudo apt-get install python-dev python3-dev
cd ~/.vim/bundle/YouCompleteMe
./install.py --clang-completer # add the path for cpp.conf
# TagBar
sudo apt install ctags

sudo apt install okular
sudo apt install chromium-browser

#zotero & tex
#zotero
udo add-apt-repository ppa:smathot/cogscinl
sudo apt update
sudo apt install zotero-standalone 
#tex 可以从安装脚本开始安装
sudo apt install perl-tk 
sudo mount -o loop texlive*.iso /mnt
cd /mnt
sudo ./install-tl -gui  */change directories
texdoc texlive-zh

#googledrive
sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt update 
sudo apt upgrade
sudo apt install grive
grive -a

#dropbox
sudo dpkg -i dropbox*.deb 
dropbox start -i

#evernote
sudo add-apt-repository ppa:nixnote/nixnote2-daily
sudo apt update
sudo apt install nixnote2

#calibre
sudo apt install calibre
#chinese
sudo apt install fcitx
sudo apt install -f
sudo dpkg -i sogoupinyin*.deb
#music
sudo apt install -f
sudo dpkg -i netease-cloud-music*.deb

#finger
#vmd
#zeo++
#vesta
#raspa

# python
sudo apt install ipython3
sudo apt install python3-matplotlib python3-numpy python3-scipy
